### ISSUE TITLE
Player scores: subset of data

### ISSUE THREAD

**Issue by Derek-Jones** [jcw024/lichess_database_ETL#1]
This is a very interesting analysis.

I am interested in looking at the growth in ranking, and don't have any interest in the details of each game.

Is it possible to obtain just player ranking details, e.g., "p1_id,p2_id,date played,p1_rating,p2_rating,result"?

I imagine that this dataset would be much smaller, and therefore quicker to download.

**Comment by jcw024** [comment]
The data pipeline as is already skips over the game moves and other bits of information to cut down on storage space. You could probably cut down more and that may reduce download speeds, but I haven't tested how much time that would save you. 

I'm sure there are plenty of opportunities to optimize the pipeline, but most of the work up to this point has been getting it to "just work" at a reasonable speed.

I added in a screenshot of the processed data to the README just to clarify what data you're actually downloading. You can compare it to the raw data to see how exactly the data is being transformed before being loaded into postgresql:
https://github.com/jcw024/lichess_database_ETL/blob/main/screenshots/processed_data.png
https://github.com/jcw024/lichess_database_ETL/blob/main/screenshots/raw_data_sample.png

If you want to modify what data you're downloading, you would need to modify these files to change the database schema (i.e. add/delete/change column names in the games table) and change the processing script to pull out only the data you want:
https://github.com/jcw024/lichess_database_ETL/blob/main/src/process_file_local.py
https://github.com/jcw024/lichess_database_ETL/blob/main/src/database_util.py
https://github.com/jcw024/lichess_database_ETL/blob/main/src/data_process_util.py

Just a warning: the pipeline will break if the data isn't _exactly_ how you've specified when you initialized the tables (in database_util.py) and troubleshooting is a pain. You would need to look at the log files stored in the airflow worker container to see what went wrong if the pipeline broke (assuming you're doing this with docker).

**Comment by Derek-Jones** [comment]
Thanks for the quick response.

Reading through the code, it looks like the bz2 files listed in:
https://github.com/jcw024/lichess_database_ETL/blob/main/src/download_links.txt
first have to be downloaded, and then a subset is stored into the database.

I want to avoid downloading the bz2 files.  Have I missed something?

**Comment by jcw024** [comment]
The bz2 files are how lichess releases their public chess game data. I don't believe there is any way around that without having access to their internal databases. I looked into streaming the data from those links and processing that bitstream data without having to download the bz2 files, but I don't think it's possible to decode the stream in that format, at least as far as I could figure out.

So unfortunately the best I could do was have the pipeline download each bz2 file, process it, then delete it. I set up the pipeline to download the next 2 bz2 files in parallel with processing the previous bz2 file so that by the time the next processing task is up, the bz2 file is already prepared to be processed.

From running the pipeline myself, the downloading component only has a minimal contribution to the total flowtime. It's the processing that's the real bottleneck on the pipeline. Since they are being deleted after processing, they shouldn't use up too much space relative to the amount of data being stored in the database.

**Comment by Derek-Jones** [comment]
I was wondering whether you had looked at storing your much smaller (relatively) files using Github's Large File Storage:
https://git-lfs.github.com/

**Comment by jcw024** [comment]
thanks for the suggestion, I was wondering about how to store some of the csv files that exceeded the 100mb limit. I added those csv files to lfs.

**Comment by Derek-Jones** [comment]
Thanks, I have cloned the update.

The column names for the file: min_max_ratings_per_player.csv.bz2
are:
   player,event,min,max,min,max
I suspect they should be:
   player,event,min,max,min_date,max_date

The last column of the file: total_blitz_games_per_player_over_time.csv.bz2
should just be a number, i.e., not a time or a string.

Is total_blitz_games_per_player_over_time.csv.bz2 a subset of
the games?  It has 41 million rows, and there are 2 billion games.

I was after information on both players in a match, so I could try out something like network regression, using (say) the the sna package in R.

**Comment by jcw024** [comment]
good catch, I renamed the last 2 columns to min_date, max_date in min_max_ratings_per_player.csv. the columns names came directly from a SQL query and I don't think I used that file for any analysis.

you are right about the total_blitz_games_per_player_over_time file. the last column was the output from a SQL query and I think I couldn't figure out how to get the result as an int using SQL, so I just did the conversion in python when making the plots. It's kind of a hacky workaround and I'm sure there's a "proper" way to do it, but I don't want to/don't have the time to rewrite/retest the code to make the plots since it assumes the data is in this format.

that file is just a subset and an aggregation of all games. 1. it only includes one time control 2. the data is not of individual games, but the lowest rating each player reached in a particular day. I chose the lowest rating to be conservative about a player's true strength as reflected in their rating. 3. it only includes games where the rating change is less than 30 (to avoid games played while under a provisional rating) 4. the dataset I have only has 450 million games

none of the csv files contain all of the database data. they are just outputs from SQL queries I ran for this particular analysis. If you want info on pairs of players, you would need to get the data for each individual game played, which means you would have to work with more rows than if the data were aggregated.

**Comment by Derek-Jones** [comment]
Sorry, delayed reply.

I was hoping you would upload some subset of the data outlined in the original issue.

Downloading gigabytes, which mostly gets thrown away does not appeal.

**Comment by jcw024** [comment]
Here's what I think you are looking for. The data only goes from 2013-2015 because having the data unaggregated/detailed to the individual games increases the amount of data. Any farther than that and you start hitting the limits on lfs

https://github.com/jcw024/lichess_database_ETL/blob/main/analytics/query_out_storage/blitz_game_pairs_2013-2015.csv.bz2

**Comment by Derek-Jones** [comment]
Great, thanks.  This is what I was after.

I will let you know how I get on.
